name: The Envelope
favicon: null
layout_spectrum: 0.9478053392376751
typography_spectrum: 0.5138718250673264
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.6695963745005429
  lightness: 0.4339572684839368
  saturation: 0.7111979252658784
  rhythmicContrast: 0.7642883106600493
purpose: []
